# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-28 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
