# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-28 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190128_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogsServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('dog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Dog')),
            ],
            options={
                'db_table': 'dog_service',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='dog',
        ),
        migrations.AddField(
            model_name='service',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Owner'),
        ),
        migrations.AlterField(
            model_name='service',
            name='dogwalker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.DogWalker'),
        ),
        migrations.AlterField(
            model_name='service',
            name='finish_service',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_service',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dogsservices',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_dog', to='api.Service'),
        ),
    ]
